### ISSUE TITLE
Usage swagger en OAS 3.1 vs 3.0

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#105]
Issue BYTEL 
Face à des problématiques d'outillage de développement pas mature sur l'OAS 3.1, nous souhaitons aborder le sujet de revenir en OAS3.0.

A noter que l'OAS 3.0 est préconisé vs 3.1 justement en raison de cette problématique d'outillage. Cf. fichier ADR dans la library common.

**Comment by richard-olvera** [comment]
Point à monter

**Comment by richard-olvera** [comment]
à cloturer je pense la bascule en 3.0 a été faite
