### ISSUE TITLE
Ajouter l'objet PM dans une malfaçon de type MalfaconOiPbo

### ISSUE THREAD

**Issue by NicolasGuilbert** [before-interop/malfacon#112]
Dans l'atelier A4, il est dit : 
![image](https://github.com/user-attachments/assets/bca7ea96-4fed-43f9-a50d-fb5e350d8972)

Hors le swagger actuel ne permet pas de renseigner le PM sur ce type de Malfaçon 
![image](https://github.com/user-attachments/assets/36dbe8f3-0052-45b2-b1b5-af6638e04c86)

**Comment by richard-olvera** [comment]
ajouté  dans la #119
