### ISSUE TITLE
Ajouter le champs activationRate

### ISSUE THREAD

**Issue by NicoTest22** [before-interop/malfacon#12]
Le taux d'activation est un pourcentage représentant le nombre de lignes activées par l'OC sur l'élément de réseau (PM ou PBO) divisé par le nombre total de lignes activées pour l'ensemble des OC. 

Ce champs doit être ajoutée en facultatif lors de l'initialisation du ticket.

Il complète le champs ocNumber sur le cas des malfaçons non imputables.

**Comment by NicolasGuilbert** [comment]
Proposition validée en GT Interop. La modification doit être réalisée : ajout de activationRate en facultatif sur le ticket. C'est un pourcentage. 
Description = Le taux d'activation est un pourcentage représentant la part de lignes activées par l'OC sur l'élément de réseau (PM ou PBO)

**Comment by marcel-ferreira** [comment]
ajouter readOnly sur OcNumber et sur activationRate

**Comment by ggrebert** [comment]
OcNumber doit être supérieur ou égal à 1 et obligatoire (dans description).
Merger dès que la modif est faite.

**Comment by richard-olvera** [comment]
J'ai modifié le swagger à relire

**Comment by NicolasGuilbert** [comment]
ok à merger suite au GT Interop 25/04
