### ISSUE TITLE
Restreindre les champs modifiables

### ISSUE THREAD

**Issue by NicoTest22** [before-interop/malfacon#15]
Une fois un ticket initialisé, les seuls champs modifiables doivent être :
- resolutionOwner, 
- Status, 
- statusChangeReason, 
- statusChangeDetails, 
- inseeCode
Et trois champs modifiables post création du ticket :
referenceSignalisationOc, reconveryQuantity, activationRate

**Comment by JulienB-O** [comment]
https://github.com/before-interop/malfacon/pull/41

**Comment by NicolasGuilbert** [comment]
Pas encore assez mûr

**Comment by NicolasGuilbert** [comment]
Ce commentaire remplace la demande initiale.
Voici la liste des champs modifiables lors de la vie d’un ticket. 
P
our chaque champ, nous indiquerons à quel statut il sera autorisé de le modifier :

-Creating / Acknowledged / In Progress / Resolved / Closed / Rejected / Canceled
champs modifiable :  status / statusChange / statusChangeDetails

-	In Progress : 
champs modifiable : resolutionOwner / RecoveryQuantity / External Id

-	In Progress / Pending
champs modifiable :  maxResolutionOcDuration (value/reason)

**Comment by NicolasGuilbert** [comment]
Prendre en compte le commentaire ci-dessus :

1) au niveau description du swagger

2) dans le readme, apporter les deux modifications suivantes:

A) rechercher "ACKNOWLEDGED → IN_PROGRESS: Le ticket est en cours de résolution" et ajouter dans ce § "L'OC peut renseigner l'identifiant du ticket au sein de son propre SI dans le champs External Id".

B) rechercher "Délai max de validation OI". Juste **avant** , dans la partie qui parle de la gestion de crise, renommée en gestion de situation exceptionnelle par une autre issue, ajouter "l'allongement de ce délai pourra être réalisé aux états In Progress et Pending via le champs maxResolutionOcDuration (value/reason)

**Comment by NicolasGuilbert** [comment]
ok à merger suite au GT Interop 25/04
