### ISSUE TITLE
Définir le format photo autorisé

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#16]
Il faudrait que le protocole malfaçon accepte à minima les mêmes formats de photo que le CRI
JPEG ou PNG sont les deux types de photos permis dans CRI 1.1 et ça ne change pas dans CRI 2.0

**Comment by ggrebert** [comment]
le protocole accepte déjà ces formats:

![image](https://github.com/before-interop/malfacon/assets/1737774/3beb747d-3659-4c42-b9f3-d52f7ed1ebea)

La question est donc: est-ce trop permissif ?

**Comment by alexisthethe** [comment]
Dans le README, la description du protocole insiste plusieurs fois sur le fait que la photo doit être en JPEG. Dans ce cas, il faut changer le README

**Comment by marcel-ferreira** [comment]
attachment catégorisé : photo ou autre type (par ex. excel si route optique)
si photo, idem CRI  : jpeg, png.

**Comment by NicolasGuilbert** [comment]
Proposition validée au GT Interop. Rien de doit être modifiée au niveau swagger car il est déjà possible de créer un attachment png ou jpeg.
Il faut par contre modifier le readme  : rechercher "JPEG" en majuscule et le remplacer par "JPEG ou PNG".
Il y a 5 occurrences à modifier.

**Comment by marcel-ferreira** [comment]
A merger
