### ISSUE TITLE
Préciser cas de gestion "Reprise par OI nonf inalisée"

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#19]
Lorsque l'OI reprend la main sur la malfaçon pour en réaliser la reprise, si celle-ci ne peut aboutir, le protocole doit indiquer terminer le processus (assurer que le processus se termine : etat final, causes,..)

**Comment by marcel-ferreira** [comment]
ticket repris par l'OI : malfaçon traitée ou non pas l'OI. distinguer ces cas dans code clôture.
- reprise par l'OI :
- clôture sans reprise : statusChangeReason OI_RESOLUTION_IMPOSSIBLE

**Comment by marcel-ferreira** [comment]
Ajouter un status Changereason distinguer cas où l'OI ne peut pas reprendre (ne peut être repris que par l'OC) du cas où l'OI renonce à reprendre.
statusChangeReason : OI_RESOLUTION_RENUNCIATION

**Comment by NicolasGuilbert** [comment]
Proposition validée en GT Interop : ajouter le statusChangeReason = OI_RESOLUTION_RENUNCIATION lors du passage de Resolved à Close par l'OI. 

1) Modification à faire dans les énumérations du swagger

2) Modifier le readme ci-dessous :
_RESOLVED → CLOSED: cloture du ticket.
Ce changement de status est effectué par l'OI. Le statusChangeReason peut être:
    RESOLVED_OC_VALIDATED
    RESOLVED_OI_VALIDATED
    OI_VALIDATION_DELAY_EXPIRED : passage automatique suite au dépassement du délai de validation OI sur une résolution OC_
   ###  **OI_RESOLUTION_RENUNCIATION : clôture sans reprise par l'OI**

**Comment by marcel-ferreira** [comment]
A merger
