### ISSUE TITLE
Statuer sur le maintien de l'état Cancelled dans le diagramme d'états.

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#20]
Statut cancelled à garder ou à supprimer dans le protocole. En cas de suppression de cet état, les tickets seront clos avec un sous motif associé pour indiquer la nature.  
l'etat cancelled est un état final, qui permet de distinguer plus facilement les états de clôture sur les tickets ayant donné lieu à un traitement opérationnel (cela simplifie le tri notamment pour la production des KPI)
Cet état est couramment utilisé sur d'autres protocoles. 
pas de gain significatif à le supprimer.

**Comment by marcel-ferreira** [comment]
statut canceled maintenu.

**Comment by NicolasGuilbert** [comment]
Le GT Interop a validé le maintien de l'état Canceled. Par contre dans le readme et le swagger, il est pafois fait mention de CANCELLED et parfois de CANCELED. 

Le GT Interop a demandé de mettre CANCELED (donc avec un seul L) partout, et en cohérence avec anomalie adresse.
Il faut donc remplacer sur le readme et le swagger tous les CANCELLED par CANCELED

**Comment by marcel-ferreira** [comment]
A merger.
