### ISSUE TITLE
fixer le délai max de reprise par l'OI

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#21]
le protocole prévoit qu'il n'est pas possible de déposer une nouvelle sig malfaçon lorsqu'il y en a une en cours sur le même élément d'infra. 
pour éviter de bloquer le dépot de nouvelles signalements, il est nécessaire d'assurer que toutes les signalisations en cours se terminent (ne pas autoriser un état à persister indéfiniment).
dans le cas d'une reprise par l'OI, Orange propose de borner le temps de traitement par l'OI (durée à fixer dans le contrat).
une clôture auto sera générée à expiration du délai, avec un motif approprié

**Comment by marcel-ferreira** [comment]
pas de délai max de reprise OI.
l'OI devra clore le ticket au bout d'un délai pour pouvoir redéposer une malfaçon sur le même élément d'infra.
délai fixé par l'OI.

**Comment by NicolasGuilbert** [comment]
Le GT Interop a validé la suppression du délai max de reprise OI.

Il faut modifier le readme et le swagger. 

Dans le reamde, rechercher "de reprise OI" : 3 instances trouvées 

1) : supprimer le § ci-dessous :
_Délai max de reprise OI
Ce délai correspond au temps maximum alloué à l'OI pour résoudre la malfaçon. Il démarre lors du passage à IN_PROGRESS avec resolutionOwner=OI._

2) supprimer le paragraphue ci-dessous :
_Délai max de reprise OI
Compteur totalResolutionOiDuration qui démarre au passage du ticket en résolution OI donc à in_Progress avec resolutionOwner=OI. Ce délai correspond au temps maximum alloué à l'OI pour résoudre la malfaçon._

3) Modifier la phrase ci-dessous : supprimer OI_DELAY_EXPIRED et ne conservver que CANCELED
_Ce changement de status est effectué par l'OI et correspond au dépassement du délai de reprise OI. Le statusChangeReason = 'OI_DELAY_EXPIRED' ou "CANCELED"


Dans le swagger : 
- supprimer le statusChangeReason = OI_DELAY_EXPIRED
