### ISSUE TITLE
supprimer les engagements de l'OI sur une réponse (délai max de réponse)

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#23]
SFR demande que le protocole n'impose pas un engagement de l'OI sur des délais (de réponse ou de reprise).

**Comment by ggrebert** [comment]
est-ce que la demande consiste à supprimer le champs `maxRsolutionOcDuration` ?

Si c'est le cas, il y a sûrement un conflit avec les issues #25 et #26

**Comment by NicolasGuilbert** [comment]
Suite à la décision prise en GT Interop rappelée ci-dessus, il faut modifier le readme : 

Remplacer la phrase "Tout ticket au-delà pourra être rejeté par l'OC dès lors qu'il a déjà un ticket sous sa responsabilité en cours sur cet élément d'infra." (1 seule instance trouvée), 
par
"Tout ticket au-delà pourra être rejeté par l'OC dès lors qu'il existe déjà un ticket en cours sur cet élément d'infra."

**Comment by marcel-ferreira** [comment]
A merger
