### ISSUE TITLE
supprimer le transfert automatique de responsabilité de l'OC vers l'OI

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#24]
SFR propose de ne pas rendre automatique le changement de propriétaire du ticket à expiration du délai  de reprise OC

**Comment by ggrebert** [comment]
A t'on plus de détail sur la proposition ou ce n'est juste qu'une suppression de fonctionnalité ?

**Comment by marcel-ferreira** [comment]
traité avec le mécanisme de changement de délai par l'OI (cf. issue #xx)
