### ISSUE TITLE
Allonger le délai de reprise OC

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#25]
SFR propose de permettre à l'OI d'allonger le délai  de reprise par l'OC (avant de reprendre en lieu et place de l'OC).

**Comment by ggrebert** [comment]
c'est déjà possible avec `maxRsolutionOcDuration`

![image](https://github.com/before-interop/malfacon/assets/1737774/c2af1ae4-f90a-4dea-880a-900211fbd2b5)
