### ISSUE TITLE
Gérér le délai dans les situation exceptionnelles

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#26]
dans le cas de situations exceptionnelles (intémpéries) il est proposé d'allonger le délai max de reprise OC, sur un crière géographique (par ex. code INSEE des communes concernées).
SFR propose d'ajouter d'autres critères.

**Comment by ggrebert** [comment]
serait-il possible d'avoir une liste de ces critères ?

**Comment by marcel-ferreira** [comment]
délai tracé dans le ticket, le code INSEE permet de périmétrer les tickets concernés par le nouveau délai. s'applique sur les rtickets en cours et les nouveaux tickets.
critère coté OI.
ajouter période /plage temporelle.
valeur du délai modifiable par l'OI au cours de la vie du ticket.
issue à clore.

**Comment by marcel-ferreira** [comment]
déjà décrit dans la doc

**Comment by NicolasGuilbert** [comment]
Décision en GT Interop de renommer "de crise" par "situations exceptionnelles"

Rechercher dans le readme "de crise" (3 instances) et remplacer par "de situations exceptionnelles"

**Comment by NicolasGuilbert** [comment]
ok à merger suite au GT Interop 25/04
