### ISSUE TITLE
Ajouter des cas dans les motifs  statusChangeReason

### ISSUE THREAD

**Issue by marcel-ferreira** [before-interop/malfacon#30]
Orange propose d'ajouter des cas de statusChangeReason sur la contestation (in progress/pending puis pending/cancelled) : 
- Ajout de « ref inexistante » ou « OC non présent sur équipement impacté »
- Ajouter du mauvais cas OC identifié
- Code insee incohérent
- Triplet localisation/localisationDetails/faultDetails inexistant
- Incohérence entre imputable et nombre d'OC
- Activation Rate non fourni (fonction de l'OI)

**Comment by NicolasGuilbert** [comment]
Les statusChangeReason existant sont suffisants.
