### ISSUE TITLE
Endpoint POST doit permettre à un OC de créer des MalfaconOc

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#31]
Le endpoint de création de ticket ne permet de créer que des MalfaconOi.
Il ne permet donc pas à l'OC de déclarer des MalfaçonOc.

Solution : ajouter MalafconOiOne dans les Malfaçon à passer en entrée de méthode POST

**Comment by ggrebert** [comment]
Need to be fixed
