### ISSUE TITLE
Contraindre les valeurs possibles de localizationDetails et codeFault pour chaque typologie de Malfacon

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#32]
Dans le swagger, pour la sous classe de MalfaconOiPm , définir dans les champs  localizationDetails et codeFault uniquement la liste des valeurs possibles pour un défault au PM et ne pas avoir toute la liste autorisée.
Idem pour les autres sous classes MalfaconOiPbo, MalfaconOiCcf et MalfaconOiAmontPm.

Idem pour les sous classes MalfaconOc.

**Comment by ggrebert** [comment]
En attente de clarification de l'issue #27 pour proposer une PR

**Comment by NicolasGuilbert** [comment]
OK comme vu en interop, à intégrer dans le main
