### ISSUE TITLE
Cas d'usage du motif CONTESTATION_ORDER_PUT_INTO_SERVICE_FOR_MORE_THAN_A_YEAR

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#33]
Dans certains cas la contestation sur motif  CONTESTATION_ORDER_PUT_INTO_SERVICE_FOR_MORE_THAN_A_YEAR pourrait s'appliquer sur des signalisation au PBO et pas uniquement sur des signalisation CCF.  Point à débattre et si c'est bien partagé à préciser dans la spec git.

**Comment by NicolasGuilbert** [comment]
Proposition validée en interop.
Dans le readme, remplacer "Ne s'applique qu'à des signalisations CCF." par "Ne s'applique qu'à des signalisations CCF et PBO."
