### ISSUE TITLE
Définir la signification et la règle de valorisation du codeInsee

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#35]
Sur l'objet Malfaçon il a y a le codeInsee qui est utile de bien cibler la commune d'intervntion.
Est il bien le codeInsee de la commune sur laquelle le défaut est constaté ? Le préciser sur le swagger pour que ce soit clair.

Qu'en est il de sa valorisation pour une malfaçon CCF dont : la PTO est sur une commune et le PBO sur une autre ?
Préciser la règle de valorisation.

Qu'en est il pour une Malfacon Amont PM ? Est ce le codeInsee du PM ou le codeInsee de l'endroit précis ou  le défaut est constaté  en amont du PM ?
Préciser la règle de valorisation.

**Comment by marcel-ferreira** [comment]
le code INSEE est dans le bloc adresse de l'équipement concerné.
il n'est pas véhiculé par le protocole sur les PM (dans l'IPE).

**Comment by marcel-ferreira** [comment]
suppression du code INSEE dans le ticket.
localisation par équipement.
