### ISSUE TITLE
Définir l'unité du champ totalResolutionOcDuration

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#36]
Le swagger précise que c'est un nombre.

Préciser l'unité : seconde, minute, jour, ... Le plus simple étant de gérer des secondes (granularité la plus fine).
Il ne fadurait pas que certains positionnent des minutes ou des jours par exemple et d'autres de ssecondes.

**Comment by ggrebert** [comment]
use seconds only
