### ISSUE TITLE
Ajout du délai max de dépot

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#37]
Pour être traité informatiquement et avoir une valeur partagée informatiquement, est il possible que l'OI valorise un champ 
delaiMaxDepot au niveau du ticket qui correspond au délai contractuel convenu entre l'OC et l'OI ?

**Comment by marcel-ferreira** [comment]
cadrage atelier A4 : granularité  des signalisations par type de malfaçon/OC/élément d'infra.
l'OI détecte plusieurs types de malfaçons sur un équipement. Il y aura  autant de sig que de types de malfaçon. Le protocole doit ermettre de traiter l'ensemble des malfaçons sur le même élément d'infra :
- L'OI enverra toutes ces sig dans la journée.
- l'OC qui recoit doit accepter les sig sur le même élément d'infra qui arrivent dans la journée. l'OC peut regrouper ses interventions pour intervenir 1 seule fois au PM. L'OC peut rejeter une sig sur un élément d'infra dès qu'une SIG est en cours

**Comment by NicolasGuilbert** [comment]
Suite à la décision du GT Interop, il faut modifier le readme au niveau du paragraphe "Délai max de dépôt entre les tickets auprès d'un même OC sur un même élément d'infra (Gestion des compléments de signalisations)"

Remplacer le passage 
"l'OI doit veiller à signaler l'ensemble des malfaçons auprès d'un même OC sur un « même élément d'infra* » dans un « délai max de dépôt entre les tickets »."
par
"l'OI doit veiller à signaler l'ensemble des malfaçons auprès d'un même OC sur un « même élément d'infra* » dans la même journée, et donc au plus tard à 23h59»

**Comment by NicolasGuilbert** [comment]
Merci de prendre en compte la décision Interop et donc la modification demandée ci-dessus

**Comment by NicolasGuilbert** [comment]
ok à merger suite au GT Interop 25/04
