### ISSUE TITLE
Ajouter les objets pour définir les routes optiques constatées et théoriques

### ISSUE THREAD

**Issue by ericjacq92** [before-interop/malfacon#38]
Il manque dans le swagger sur les objets Malfacon des objets/champs permettant de définir les routes optiques constatées et théoriques dans les cas ou il n'y a pas de pièces attachées :
- PBO / ROUTE OPTIQUE / Reprise sauvage Route Optique par casse soudure au PBO
- PBO / ROUTE OPTIQUE / Raccordement de site non déployé dans IPE
- PBO / ROUTE OPTIQUE / Non respect Route Optique communiquée
- PM / ROUTE OPTIQUE / Non respect Route Optique communiquée
Ces objets doivent définis à la création et à la résolution.

**Comment by marcel-ferreira** [comment]
conformément à la note de cadrage, les routes optiques seront fournies au format du protocole Accès:
NomModulePm : obligatoire si route PM
PositionModulePm: obligatoire si route PM
ReferenceCableModulePm : facultatif
InformationTubeModulePm : facultatif
InformationFibreModulePm : facultatif
InformationTubePBO : obligatoire si PBO
InformationFibrePBO: obligatoire si PBO
ReferenceCablePBO : facultatif si PBO
A ces champs Accès, on peut ajouter 2 champs facultatifs:
ExpectedPTO
Reference ONT  (MAC ou SN)

Au dépôt de la sig :
- une même sig pour chaque type de route :la sig  peut porter sur plusieurs routes 
- pour chacune, fournir la route constatée (obligatoire), la route théorique (facultatif OI), 
dans la réponse : la route optique corrigée (obligatoire).

**Comment by NicolasGuilbert** [comment]
En complément modification du readme: 
1) rechercher "au sein d'un "attachment"," et supprimer exactement cette partie "au sein d'un "attachment","

2) rechercher " où un attachment est attendu" et supprimer exactement cette partie " où un attachment est attendu"

3) rechercher "A ce statut une photo au format JPEG ou PNG est présente oligatoirement" et ajouter derrière obligatoirement (sauf cas des routes optiques)

4) rechercher "et une photo obligatoire au format JPEG ou PNG illustrant la résolution de la malfaçon", il y en a deux. Modifier uniquement celui de la partie OI critique ou non imputable pour ajouter derrière "sauf cas des routes optiques"

5) rechercher "La signalisation porte obligatoirement une photo illustrant la malfaçon." et ajouter "sauf cas des routes optiques"

**Comment by ericjacq92** [comment]
Coté Bytel nous souhaitons avoir systématiquement  l'intégralité des informations de RouteOptique :
- NomModulePm 
- PositionModulePm
- ReferenceCableModulePm 
- InformationTubeModulePm
- InformationFibreModulePm
- InformationTubePBO
- InformationFibrePBO
- ReferenceCablePBO
- ExpectedPTO
Que ce soit pour une malfaçon localisée PBO ou PM.
C'est nécessaire pour assurer les bons travaux sur le terrain.
