### ISSUE TITLE
Définir la position géographique de tous les équipement Infra pouvant faire l'objet d'une malfaçon

### ISSUE THREAD

**Issue by svernierAI** [before-interop/malfacon#42]
L'objet GeographicAddress semble avoir bien été rajouté sur tous les éléments d'INFRA PM, PBO, PTO. 
Mais elle ne semble pas contenir l'objet Localization (type GeographicPoint). Il serait utile de le rajouter

**Comment by ggrebert** [comment]
Doit-on ajouter GeographicPoint à l'objet PTO ?

**Comment by svernierAI** [comment]
Pour ma part, oui vu que l'objet adress est ajouté.
Par contre, dans ce cas il faudra supprimer l'objet localization qui est dans l'objet MalfaconOiCcf qui serait en doublon

**Comment by marcel-ferreira** [comment]
A clore
