### ISSUE TITLE
Manque de clarification sur l'état CREATING

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#45]
Il faut mieux spécifier l'état CREATING.

Notamment, que se passe-t-il si la PJ n'est jamais ajoutée ?
Voici notre proposition : Après un délai (à définir au niveau protocole. Ex: 24h), le ticket passe au statut REJECTED avec un statusChangeReason dédié PHOTO_MISSING

**Comment by ggrebert** [comment]
+1
par contre, je pense qu'on pourrait simplement supprimer le ticket pour que ce genre de cas ne rentre pas dans les KPI.

**Comment by marcel-ferreira** [comment]
OK pour suppression.

**Comment by NicolasGuilbert** [comment]
Suite aux échanges interop, la proposition est la suivante, que ce soit pour un ticket créé par l'OI ou par l'OC : 
- toute signalisation à l'état creating depuis 24h doit être supprimée 
- aucune notification ne doit être faite sur l'état creating 

Modification à apporter dans le readme: 
- rechercher "Initialisation : statut CREATING" ==> 3 instances 
- ajouter dans ces 3 paragraphes les 2 règles de gestion ci-dessus

**Comment by alexisthethe** [comment]
Axione: OK pour la règle proposée

**Comment by NicolasGuilbert** [comment]
ok à merger suite au GT Interop 25/04
