### ISSUE TITLE
Notes/commentaires libres

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#46]
il faut qu'on puisse ajouter des notes sur 1 ticket librement (sans conditions) des 2 côtés.

**Comment by ggrebert** [comment]
Il avait déjà été décidé de ne pas autoriser cette fonctionnalité dans ce protocole.
voir: https://github.com/before-interop/malfacon/issues/17

**Comment by alexisthethe** [comment]
La proposition ne nous convenait pas justement côté Axione, et je crois pour d'autres opérateurs si je me rappelle bien la dernière réunion

**Comment by svernierAI** [comment]
Côté AltitudeInfra, on avait également remonté en GT le manque d'Endpoint pour échanger des Notes. Je pense qu'il est nécessaire qu'elles soient existantes.

**Comment by marcel-ferreira** [comment]
Orange ne souhaite pas l'implémentation de la fonctionnalité « Note » dans ce protocole.
Étant donné que nous n’avons pas d’obligation de lire les notes et que ces notes ne pourront pas faire l'objet de réclamation, cela pourrait créer des incompréhensions.
Si les notes sont malgré tout incluses dans ce protocole suite à une décision de la majorité des opérateurs présents, nous ne garantissons pas la mise en place cette fonctionnalité dans SI d’Orange

**Comment by marcel-ferreira** [comment]
sera implémenté dans le protocole.(yc Orange)
