### ISSUE TITLE
Proposition de changer le endpoint "GET / Get all tickets"  par "POST /search Search tickets" ou "POST /filter Filter tickets"

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#53]
Ce endpoint va être utiliser pour la recherche/filtre de tickets. Donc les champs de filtre peuvent être très long (exemple on cherche un gros morceau de texte). Et comme la méthode GET ne permet de rensiegner les champs de la recherche dans les paramètres URL et que l'URL a une longueur maximale fixe, je conseille plutôt de passer par une méthode POST avec des paramètres JSON dans le body : 

On peut nommer le endpoint "/search" ou "/filter" selon ce qui vous semble le plus pertinent

**Comment by alexisthethe** [comment]
Idem pour la requête HEAD => POST /count

**Comment by ggrebert** [comment]
Il est techniquement possible d'ajouter un body à une requête de type GET ou HEAD.
Certes, ce n'est pas une pratique standard, mais elle est utilisée sur Mongo ou EalsticSearch.

Par contre, je ne pense pas que cette limite de taille d'url soit un réel problème en 2024:
- Il existe une limite à 2048 caractères sur IE. Mais pas sur les autres browser.
- La véritable limite est 8kb: ce qui est vraiment énorme pour un filtre

**Comment by alexisthethe** [comment]
J'ai déjà eu ce genre de problème (pour des recherche de textes longs"). Mais je ne sais pas si dans ce protocole nous aurons cette limite. A discuter...

**Comment by ggrebert** [comment]
rejected
