### ISSUE TITLE
Le etag pour les Attachments est inutile

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#55]
référence : https://github.com/before-interop/malfacon/blob/main/openapi.yaml#L309

Les attachment n'ont pas la possibilité d'être modifiée. Donc il me semble inutile de gérer un etag pour les attachments. 

je proposerai de supprimer cette information pour les attachments et par conséquent les champ "If-Match", "If-None-Match", "If-Modified-Since", "If-Unmodified-Since",

**Comment by ggrebert** [comment]
pourquoi pas.
certains OI pourront le garder s'il le souhaite, mais en supprimant ce header du swagger, on le rend optionnel.
