### ISSUE TITLE
Faut-il un champ "Offset" pour les télécharger les attachments

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#56]
J'imagine que le champ "Range" de la méthode `/{malfaconId}/attachment/{attachmentId}/content` permet de télécharge la pièce jointe par chunk..
Dans ce cas, ne manque-t-il pas un champ "offset" pour télécharger les chunks suivants ?

Sinon à quoi sert ce champ "range" ?

**Comment by ggrebert** [comment]
En effet, `Range` sert à télécharger les pièces jointe par chunk.
C'est un header standard qui n'a pas besoin de `offset` supplémentaire car la valeur est déjà renseigné dans `Range`:

```
Range: <unit>=<range-start>-<range-end>
```

doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

**Comment by alexisthethe** [comment]
Ah oui en effet autant pour moi 👍
