### ISSUE TITLE
Le endpoint HEAD /event est-il vraiment utile ?

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#57]
Je ne vois pas l'utilité de la méthode HEAD /event 

A-t-on un scénario ou un cas d'usage pour lequel ce endpoint est utile ?

Et si les events sont postés chez l'OC, la méthode HEAD /event  ne devrait-elle pas plutôt être implémentée par l'OC ?

**Comment by alexisthethe** [comment]
Idem pour le GET /event qui est d'ailleurs n'est pas classé ni dans les méthodes à implémenter par l'OC ni par l'OI

**Comment by ggrebert** [comment]
les endpoints GET et HEAD ont été ajouté pour plusieurs raisons:

1. pour les petits OC
2. pour offrir à l'OC la possibilité de ce resynchroniser en cas de problème

**Comment by alexisthethe** [comment]
OK merci 👍
