### ISSUE TITLE
L'architecture proxyfiée ne doit pas être faire partie des specs

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#58]
référence : https://github.com/before-interop/malfacon/blob/main/openapi.yaml#L16

L'arcitecture proxifiée présentée ne doit pas faire partie du protocole et donc ne doit pas apparaitre dans le swagger. Chaque opérateur décide de la façon de gérer son architecture interne. Par exemple, nous n'allons pas suivre cette architecture car les pièces jointes seront gérées dans le même outil que l'outil de ticketing et non via un bucket S3.

Uniquement l'API présneté aux autres OCs doit être spécifiée dans le protocole.

Toutefois ce schéla d'architecture peut éventuellement être gardé dans le README comme exemple.

**Comment by ggrebert** [comment]
OK: on supprime

**Comment by marcel-ferreira** [comment]
A merger
