### ISSUE TITLE
@schemaLocation	?

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#61]
A quoi sert le champ @schemaLocation ? En a-t-on vraiment besoin ?

**Comment by ggrebert** [comment]
c'est un champs optionnel issue de TMF.

**Comment by ggrebert** [comment]
oui, c'est juste pratique pour faire des contrats d'interface dynamique pour un Rest client.
mais dans notre cas, ce n'est pas vraiment utile et les OI peuvent omettre ce champ

**Comment by alexisthethe** [comment]
OK très clair merci 👍
