### ISSUE TITLE
A quoi sert le statut d'une PJ ?

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#63]
Pour Attachment, on a un champ "status" qui peut prendre les valeurs suivantes "PENDING" "VALIDATED" "REJECTED".

A quoi sert ce champ ? Je n'ai pas vu de cycle de vie des PJ dans le README. Et je ne vois pas pourquoi l'OI devrait valider ou rejeter une PJ...

**Comment by ggrebert** [comment]
Héritage de common.
Utile pour la gestion antivirus

**Comment by alexisthethe** [comment]
Ah ? Je ne comprends pas.. As-tu un exemple de scénario qui illustre ça ?

**Comment by ggrebert** [comment]
exemple de l'implem que j'ai faite:

1. Envoi d'un Attachment -> status = `PENDING`
2. à ce moment là on peut récupérer les metadatas par l'API mais pas télécharger le fichier
3. analyse antivirus terminé:
  1. Analyse OK: status = `VALIDATED`: téléchargement du fichier possible
  2. Analyse KO: status = `REJECTED`: téléchargement du fichier impossible (et suppression de celui-ci)

**Comment by alexisthethe** [comment]
Ah oui d'accord 👍
