### ISSUE TITLE
schema "Error" champ "status"

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#65]
A-t-on vraiment besoin d'avoir un champ status pour le schéma de réponse Error ? Vu qu'il est redondant avec le status code HTTP

**Comment by ggrebert** [comment]
Héritage de TMF: https://github.com/tmforum-rand/schemas/blob/candidates/Common/Error.schema.json

**Comment by ggrebert** [comment]
Quand les réponses te semble satisfaisante, @alexisthethe pourrais-tu soit clôturer l'issue, soit dire que l'on puisse le faire.
C'est pout éviter de garder trop issue ouverte inutilement dans le temps.
