### ISSUE TITLE
Use ISO 3166 for Country code 

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#66]
ref : https://github.com/before-interop/common/blob/main/common/schemas/GeographicAddress.openapi.yaml#L25

Que pensez-vous de l'idée d'utiliser la norme ISO 3166 A-2 pour définir le code pays pour le champ "country" du schéma "Adressable" ?

Avec un `pattern: ^[A-Z]{2}$`. Ainsi, tous les opérateurs enverront "FR" pour la France, et on s'assure de ne pas avoir des différence comme "FRANCE", "France", "france" ou d'avoir traduction différentes entre opérateurs (ex: "Germany", "Deutschland", "Allemagne" ?).

Référence Wikipédia de la norme : https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by ggrebert** [comment]
Je pense que c'est une super idée.

**Comment by ggrebert** [comment]
Rejected
