### ISSUE TITLE
Enum pour le champ "type" de GeographicPoint

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#67]
ref: https://github.com/before-interop/common/blob/main/common/schemas/GeographicPoint.openapi.yaml#L39

Ne devrait-on pas limiter les possibilités pour le champ "type" de GeographicPoint pour se donner la possibilité de faire de la logique ou des calculs sur des coordonnées géographiques (ex de cas d'usage: calcul d'une distance entre 2 points)

Voici une proposition pour les valeurs possibles du champ "type". Cette liste avait été décidée ainsi dans le cadre du protocole Anomalie Adresse : 
* RGF93
* WGS84
* RGFG95
* RGR92
* RGM
* RGSPM

**Comment by ggrebert** [comment]
Elle sont limitée par protocole.
Ce qui permet de garantir une homogénéité du DataModel et surtout de pouvoir utiliser ce model pour d'autres choses (d'où l'attribut `z`)
