### ISSUE TITLE
Fichier common/schemas/GeographicPoint.schemas.json inutile ?

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#68]
ref: https://github.com/before-interop/common/blob/main/common/schemas/GeographicPoint.schemas.json

Ce fichier semble redondant avec le fichier common/schemas/GeographicPoint.openapi.yaml

**Comment by ggrebert** [comment]
+1
un oubli de suppression de l'époque où l'on hésité à utiliser le format [Json Schema](https://json-schema.org/).

**Comment by ggrebert** [comment]
fixed by https://github.com/before-interop/common/pull/13
