### ISSUE TITLE
schema PBO champ "statut"

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#70]
ref : https://github.com/before-interop/common/blob/main/common/schemas/Interop.openapi.yaml#L116

Il semble qu'il manque un champ "statut" au schema PBO comme pour le schema PM. D'ailleurs dans le commentaire du commissioningDate on parle de statut du PBO.

**Comment by ggrebert** [comment]
corriger la description.
le champ status n'existe pas pour le PBO

**Comment by marcel-ferreira** [comment]
Mergé
