### ISSUE TITLE
le schema StatusEntity semble redondant avec StatusChange

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#71]
ref: https://github.com/before-interop/common/blob/main/common/schemas/StatusEntity.openapi.yaml

Il semble que StatusEntity est redondant avec StatusChange. Peut-on le supprimer ?

**Comment by ggrebert** [comment]
Non, ils sont différent.

Si tu regarde bien, `StatusEntity` a un attribut [statusChange](https://github.com/before-interop/common/blob/main/common/schemas/StatusEntity.openapi.yaml#L40) qui est l'historique des status.

`StatusEntity` est le status courant de l'entité, `StatusChange` est l'historique des status de la dite entitée.

**Comment by alexisthethe** [comment]
OK merci pour la précision :)
