### ISSUE TITLE
La méthode "Update all Attachment" devrait être PUT et non PATCH

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#72]
refs : https://github.com/before-interop/common/blob/main/tools/attachment/attachment.openapi.yaml#L193

La méthode "Update all Attachment" devrait être PUT et non PATCH

**Comment by ggrebert** [comment]
Tu ne peux pas faire un PUT sur un update en masse

**Comment by alexisthethe** [comment]
Ah ok je ne savais pas ça
