### ISSUE TITLE
Implémentation de la méthode "stream-event" optionnelle

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/malfacon#73]
ref : https://github.com/before-interop/common/blob/main/tools/attachment/attachment.openapi.yaml#L44

L'implémentation de la méthode "stream-event" ne devrait pas être obligatoire.

Nous ne souhaitons pas l'implémenter, elle devrait être optionnelle. Et dans ce cas cela ne doit pas apparaître dans le protocole interop.

**Comment by ggrebert** [comment]
c'est dans Tools, donc pas obligatoire.
elle n'est ni dans AnoAdresse, ni dans Malfacon
